# Generated by Django 5.0.6 on 2024-05-31 02:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=60, verbose_name='NombreCliente')),
                ('Email', models.EmailField(max_length=45, verbose_name='Email')),
                ('Direccion', models.CharField(max_length=45, verbose_name='Direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreDirector', models.CharField(max_length=60, verbose_name='NombreDirector')),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionGenero', models.CharField(max_length=60, verbose_name='DescripcionGenero')),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TituloPelicula', models.CharField(max_length=128, verbose_name='TituloPelicula')),
                ('AnioLanzamiento', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='AnioLanzamiento')),
                ('Duracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Duracion')),
                ('PrecioAlquiler', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PrecioAlquiler')),
                ('Disponibilidad', models.BooleanField(verbose_name='Disponibilidad')),
                ('URLCartel', models.CharField(max_length=150, verbose_name='URLCartel')),
                ('Director_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.directores')),
                ('Genero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.generos')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicio', models.DateField(verbose_name='FechaInicio')),
                ('FechaFin', models.DateField(verbose_name='FechaFin')),
                ('PrecioTotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='PrecioTotal')),
                ('Estado', models.BooleanField(verbose_name='Estado')),
                ('Cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.clientes')),
                ('Pelicula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.peliculas')),
            ],
        ),
    ]
