# Generated by Django 5.0.6 on 2024-06-14 23:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreDirector', models.CharField(max_length=60, verbose_name='Director')),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescripcionGenero', models.CharField(max_length=60, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TituloPelicula', models.CharField(max_length=128, verbose_name='Título')),
                ('AnioLanzamiento', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año de Lanzamiento')),
                ('Duracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Duración')),
                ('PrecioAlquiler', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Alquiler')),
                ('Disponibilidad', models.BooleanField(verbose_name='Disponibilidad')),
                ('URLCartel', models.ImageField(upload_to='carteles/', verbose_name='Poster')),
                ('Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.directores')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.generos')),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaInicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('FechaFin', models.DateField(verbose_name='Fecha de Finalización')),
                ('PrecioTotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Total')),
                ('Estado', models.BooleanField(verbose_name='Estado')),
                ('Cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.clientes')),
                ('Pelicula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.peliculas')),
            ],
        ),
    ]
