# Generated by Django 5.0.6 on 2024-05-24 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('idActor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreActor', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('NombreAdministrador', models.CharField(max_length=60)),
                ('ContrasenaAdministrador', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('idDirector', models.AutoField(primary_key=True, serialize=False)),
                ('NombreDirector', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('idPelicula', models.AutoField(primary_key=True, serialize=False)),
                ('NombrePelicula', models.CharField(max_length=128)),
                ('FechaEstreno', models.DateTimeField(blank=True, null=True)),
                ('URLCartel', models.CharField(max_length=150, null=True)),
                ('Director_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.directores')),
            ],
        ),
        migrations.CreateModel(
            name='ActoresenPeliculas',
            fields=[
                ('idActoresenPeliculas', models.AutoField(primary_key=True, serialize=False)),
                ('Papel', models.CharField(max_length=128)),
                ('Actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.actores')),
                ('Pelicula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.peliculas')),
            ],
        ),
    ]
