# Generated by Django 5.0.6 on 2024-06-18 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='CantidadDisponible',
            field=models.IntegerField(default=1, verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='FechaInicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='Disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Disponibilidad'),
        ),
    ]
