# Generated by Django 3.2 on 2024-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='URLCartel',
            field=models.ImageField(upload_to='carteles/', verbose_name='URLCartel'),
        ),
    ]
