# Generated by Django 3.2 on 2024-06-08 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_peliculas_urlcartel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peliculas',
            old_name='Director_id',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='peliculas',
            old_name='Genero_id',
            new_name='Genero',
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='FechaFin',
            field=models.DateField(verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='FechaInicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='PrecioTotal',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Total'),
        ),
        migrations.AlterField(
            model_name='directores',
            name='NombreDirector',
            field=models.CharField(max_length=60, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='generos',
            name='DescripcionGenero',
            field=models.CharField(max_length=60, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='AnioLanzamiento',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año de Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='Duracion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='PrecioAlquiler',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Alquiler'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='TituloPelicula',
            field=models.CharField(max_length=128, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='URLCartel',
            field=models.ImageField(upload_to='carteles/', verbose_name='Poster'),
        ),
    ]
